repos:
-   repo: local
    hooks:
      - id: check_code
        name: check_code
        entry: bash -c './scripts/check_code.sh'
        language: system
        types: [python]
        pass_filenames: false